---
# template source: https://github.com/bretfisher/super-linter-workflow/blob/main/templates/call-super-linter.yaml
name: Lint Code Base

on:
  
  push:
    branches: [main]
  
  pull_request:

jobs:
  call-super-linter:
    name: Call Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read # clone the repo to lint
      statuses: write #read/write to repo custom statuses
    steps:
      - name: Checkout 
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


    
 