name: Parallelize jobs

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/linters/*"
  pull_request:
    paths-ignore:
      - "README.md"
      - ".github/linters/*"
  schedule:
    - cron: "0 12 15 * *"
  workflow_dispatch:

jobs:
  # FIRST JOB ##########
  build-test-image:
    name: Build image for testing
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCRR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{github.actor}}/httpenv-ci-automation:${{github.run_id}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  # NEXT JOB ###########
  test-unit:
    name: Unit tests in Docker
    runs-on: ubuntu-latest
    needs: [build-test-image]
    permissions:
      packages: read

    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Testing in Docker
        run: |
          docker run --rm ghcr.io/${{github.actor}}/httpenv-ci-automation:${{github.run_id}} go test -v ./...
          # docker run --rm -d --name app -p 8888:8888 \
          # ghcr.io/${{github.actor}}/httpenv-ci-automation:${{github.run_id}}
          # sleep 2
          # curl -f localhost:8888 || exit 1
          # docker stop app

          echo "Unit test passed! ✅"

  # NEXT JOB ############
  test-integration:
    name: Integration test in Docker compose
    runs-on: ubuntu-latest
    needs: [build-test-image]
    permissions:
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Integration testing in Docker Compose
        run: |
          export TESTING_IMAGE=ghcr.io/${{github.actor}}/httpenv-ci-automation:${{github.run_id}}
          docker compose -f docker-compose.test.yml up --exit-code-from sut
          echo "Integration Test Passed! ✅"

  # NEXT JOB ############
  test-k8s:
    name: Testing deployment in kubernets
    runs-on: ubuntu-latest
    needs: [build-test-image]
    permissions:
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create k3d kubernetes cluster
        uses: AbsaOSS/k3d-action@v2.4.0
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

      - name: Smoke test deployment in k3d k8s
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=https://ghcr.io \
            --docker-username=${{github.actor}} \
            --docker-password=${{secrets.GITHUB_TOKEN}}
          export TESTING_IMAGE=ghcr.io/${{github.actor}}/httpenv-ci-automation:${{github.run_id}}
          envsubst < manifests/deployment.yaml | kubectl apply -f -
          kubectl rollout status deployment myapp --timeout=2m
          kubectl get pods
          kubectl describe pod -l app=myapp
          kubectl logs -l app=myapp
          kubectl exec deploy/myapp -- curl --fail localhost:8888
          echo "Testing in k8s passed! ✅"

  # NEXT JOB ##########
  scan-image:
    name: Scan Image With Trivy
    runs-on: ubuntu-latest
    needs: [build-test-image]
    permissions:
      packages: read

    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy for HIGH,CRITICAL CVEs and report(blocking)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{github.actor}}/httpenv-ci-automation:${{github.run_id}}
          exit-code: 1
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH, CRITICAL"
          format: "sarif"
          output: "trivy-results.sarif"

  # NEXT JOB #######
  build-final-image:
    name: Build final image and push to dockerhub
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration, test-k8s, scan-image]
    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Extract Docker metadata
        id: extract_meta_data
        uses: docker/metadata-action@v5
        with:
          images: devtom028/go-httpenv
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{endsWith(github.ref,github.event.repository.default_branch)}}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Docker final build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.extract_meta_data.outputs.tags}}
          labels: ${{steps.extract_meta_data.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Find comment for image tags
        uses: peter-evans/find-comment@v4
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-author: "github-actions[bot]"
          body-includes: Docker image tag(s) pushed

      - name: Create or update comment for image tags
        uses: peter-evans/create-or-update-comment@v5
        if: github.event_name == 'pull_request'
        with:
          comment-id: ${{steps.fc.outputs.comment-id}}
          issue-number: ${{github.event.pull_request.number}}
          body: |
            Docker image tag(s) pushed:
            ```text
            ${{ steps.docker_meta.outputs.tags }}
            ```

            Labels added to images:
            ```text
            ${{ steps.docker_meta.outputs.labels }}
            ```
          edit-mode: replace
